### ISSUE TITLE
VPC subnet definitions are overly restrictive

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/hpc-toolkit#215]
The current requirements for a VPC created through `resources/network/vpc` require that each subnet's address range be a sub-block of the `network_address_range` parameter.  This requirement is set by specifying subnets via a `new_bits` parameter, and the Terraform using the `cidrsubnets` function.

These requirements remove the ability for a user to precisely the define the subnets and address ranges they wish to use, as well as requires all created subnets to have a common prefix.  This prevents (admittedly obtuse) situations like subnets in a VPC containing completely different address ranges (mixing `10.` with `192.168.`, etc, etc).

I would like to see the ability to specify each subnet which should be created by explicitly defining it's CIDR, rather than setting the `network_address_range` and `new_bits` variables.

**Comment by tpdownes** [comment]
For record: we are designing a backwards-compatible solution for this extra functionality and have the implementation work planned as a high priority for the 1.x series of the Toolkit. We will update the schedule as we make progress.

**Comment by tpdownes** [comment]
This has been incorporated on the [develop branch](https://github.com/GoogleCloudPlatform/hpc-toolkit/tree/develop/community/modules/scheduler/SchedMD-slurm-on-gcp-controller#modules) of the HPC Toolkit and will be included in our next tagged release. Please see #392 for details.

We will leave this issue open until the fix is in a tagged release.
