### ISSUE TITLE
Rocky image failing due to 404 on lustre-client

### ISSUE THREAD

**Issue by javierbq** [GoogleCloudPlatform/hpc-toolkit#2733]
**If you find a similar existing issue, please comment on that issue instead of creating a new one.**

**If you are submitting a feature request, please start a [discussion](https://github.com/GoogleCloudPlatform/hpc-toolkit/discussions/new?category=ideas-and-feature-requests) instead of creating an issue.**

### Describe the bug

I am unable to either create a new image using Packer or use an init script that installs a dependency due to this error related to lustre. I am not sure why this is happening, I get the same error with any package

```
[jcastellanos@red-l4spotnodegrou-2 custom_scripts]$ sudo yum install nano
Lustre Client                                                                                                                           2.4 kB/s | 855  B     00:00    
Errors during downloading metadata for repository 'lustre-client':
  - Status code: 404 for https://downloads.whamcloud.com/public/lustre/latest-release/el8.9/client/repodata/repomd.xml (IP: 138.197.209.17)
Error: Failed to download metadata for repo 'lustre-client': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

this start happening over the weekend

yum install any package produces the same behaiviour

### Steps to reproduce

1.

### Actual behavior

What happened instead.

### Version (`ghpc --version`)
ghpc version v1.31.1
### Blueprint

If applicable, attach or paste the blueprint YAML used to produce the bug.

```yaml

```

### Expanded Blueprint

If applicable, please attach or paste the expanded blueprint. The expanded blueprint can be obtained by running `ghpc expand your-blueprint.yaml`.

Disregard if the bug occurs when running `ghpc expand ...` as well.

```yaml

```

### Output and logs

```text

```

### Execution environment

- OS: [macOS, ubuntu, ...]
- Shell (To find this, run `ps -p $$`): [bash, zsh, ...]
- go version:

**Comment by tpdownes** [comment]
@javierbq could you please attach a blueprint to your issue report? It helps us confirm the details of our response.

That said, I believe you are attempting to use a Slurm image based on Rocky Linux 8. The upstream Whamcloud/DDN repositories for Lustre have reorganized around Rocky 8.10 while the current images remain based on 8.9. We are working on updates to resolve this. It will probably include a new Slurm image based upon Rocky 8.10, though we will announce details when ready.

The pattern we recommend is to:

1. Disable the lustre-client repo
2. Upgrade your base OS to Rocky 8.10
3. Modify the lustre-client URL to point to 8.10 packages
4. Upgrade remaining packages (lustre)

A solution that would work in automated environments, by prepending this runner to your startup scripts:

```
settings:
  runners:
  - type: shell
    destination: upgrade_os_lustre.sh
    content: |
      #!/bin/bash
      dnf upgrade --disablerepo=lustre-client -y
      sed -i 's,el8.9,el8.10,' /etc/yum.repos.d/lustre-client.repo
      dnf upgrade -y
   ... # add remaining runners from your blueprint
```

**Comment by javierbq** [comment]
thamks @tpdownes. I figured out the same. I was able to work over the problem by deleting lustre from the yum repo.

**Comment by ek-nag** [comment]
@tpdownes would it make sense to lock to specific Lustre version instead of going with whatever 'latest-release' is to prevent something like this from happening in the future?

https://github.com/GoogleCloudPlatform/slurm-gcp/blob/47416536624dc9fe99ca731a8bc2d927fabbf409/ansible/roles/lustre/vars/redhat-8.yml#L15

**Comment by tpdownes** [comment]
There is a fundamental issue here in that, if you pick a specific Lustre release, Whamcloud does not support updating the minor version of RedHat OS itself. e.g., look at:

https://downloads.whamcloud.com/public/lustre/lustre-2.15.1/

I think I may be able to work around this with something like:

```
https://downloads.whamcloud.com/public/lustre/latest-release/el$releasever/client
```

but, we would to [override the default value](https://access.redhat.com/solutions/238533) of `$releasever` from `8` to `8.10`... etc.

The good news is that 8.10 is the final release of Rocky 8, so we may be able to get away with hard-coding 8.10. 8.10 will be under support through 2029.

**Comment by tpdownes** [comment]
Update:

- all future updates will use a URL with 8.10; because no new releases of Rocky 8 are planned, we believe this change will last as long as Whamcloud provides Lustre support on Rocky 8
- we pushed a minor update to the latest Rocky 8 images for the "v5" and "v6" Slurm-GCP solutions that correct the URL to use a previous release (2.15.4):

https://downloads.whamcloud.com/public/lustre/lustre-2.15.4/

Users should be aware that upgrading from 8.9 to 8.10 appears to bring in a kernel that is not compatible with luste-2.15.4 DKMS modules. In my testing, the DKMS system re-compiled the lustre modules for the new kernel, but the modules failed to load. I found it necessary to update the yum repo configuration in /etc/yum.repos.d/lustre-client.repo to the latest-release or 2.15.5 modules:

https://downloads.whamcloud.com/public/lustre/latest-release/
